apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-share-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-share-pool-sc
  resources:
    requests:
      storage: 128Gi
